version: "3.9"

services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    networks:
      - takeout-users-net

networks:
  takeout-users-net:
    driver: bridge